package exit

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"NanoKVM-Server/proto"
	"NanoKVM-Server/utils"
)

// hev.yml exactly as the spec's Data model lists it (D24 misc values).
const (
	hevLogLevel          = "warn"
	hevConnectTimeout    = 12000
	hevTCPBufferSize     = 16384
	hevUDPRecvBufferSize = 65536
	hevTaskStackSize     = 20480
	hevMaxSessionCount   = 256
)

// RenderHevConfig renders /etc/kvm/exit/<n>/hev.yml.
func RenderHevConfig(slot Slot, cfg Config) string {
	var b strings.Builder
	fmt.Fprintf(&b, "tunnel:\n")
	fmt.Fprintf(&b, "  name: %s\n", slot.Tun())
	fmt.Fprintf(&b, "  mtu: %d\n", cfg.MTU)
	fmt.Fprintf(&b, "  ipv4: %s\n", slot.TunAddr())
	fmt.Fprintf(&b, "socks5:\n")
	fmt.Fprintf(&b, "  port: %d\n", slot.SocksPort())
	fmt.Fprintf(&b, "  address: 127.0.0.1\n")
	fmt.Fprintf(&b, "  udp: 'udp'\n")
	fmt.Fprintf(&b, "misc:\n")
	fmt.Fprintf(&b, "  log-file: %s\n", slot.LogPath("hev"))
	fmt.Fprintf(&b, "  log-level: %s\n", hevLogLevel)
	fmt.Fprintf(&b, "  connect-timeout: %d\n", hevConnectTimeout)
	fmt.Fprintf(&b, "  tcp-buffer-size: %d\n", hevTCPBufferSize)
	fmt.Fprintf(&b, "  udp-recv-buffer-size: %d\n", hevUDPRecvBufferSize)
	fmt.Fprintf(&b, "  task-stack-size: %d\n", hevTaskStackSize)
	fmt.Fprintf(&b, "  max-session-count: %d\n", hevMaxSessionCount)
	return b.String()
}

// RenderRestrict renders /etc/kvm/exit/<n>/wstunnel-restrict.yml (D13): one
// restriction, matched on the path prefix and the bearer token, allowing only
// a reverse SOCKS5 tunnel onto the slot's loopback port. The token is a fixed
// alphabet with no regex metacharacters, which is what lets it sit inside the
// anchored pattern verbatim.
func RenderRestrict(slot Slot, cfg Config) string {
	var b strings.Builder
	fmt.Fprintf(&b, "restrictions:\n")
	fmt.Fprintf(&b, "  - name: %s\n", slot.Name())
	fmt.Fprintf(&b, "    match:\n")
	fmt.Fprintf(&b, "      - !PathPrefix \"^%s$\"\n", slot.ServerPathPrefix())
	fmt.Fprintf(&b, "      - !Authorization \"^Bearer %s$\"\n", cfg.Token)
	fmt.Fprintf(&b, "    allow:\n")
	fmt.Fprintf(&b, "      - !ReverseTunnel\n")
	fmt.Fprintf(&b, "        protocol: [Socks5]\n")
	fmt.Fprintf(&b, "        port: [%d]\n", slot.WstunnelReversePort())
	fmt.Fprintf(&b, "        cidr: [127.0.0.1/32]\n")
	return b.String()
}

var envSafeName = regexp.MustCompile(`^[A-Za-z0-9_.-]+$`)

// EnvPath is the file S94exit sources for this slot (see RenderEnv).
func (s Slot) EnvPath() string { return filepath.Join(s.Dir(), "env") }

// RenderEnv renders /etc/kvm/exit/<n>/env, the file S94exit sources so the
// shell never parses JSON. Every value is shell-safe by construction: the
// numbers are numbers, the mode is an enum, the NIC is filtered, and the reject
// list is rendered from the Go policy so the chain and the front door can
// never disagree about D21.
func RenderEnv(slot Slot, cfg Config, nic string) string {
	if !envSafeName.MatchString(nic) {
		nic = ""
	}
	bit := func(b bool) string {
		if b {
			return "1"
		}
		return "0"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by NanoKVM-Server from %s; sourced by S94exit\n", slot.ConfigPath())
	fmt.Fprintf(&b, "SLOT=%s\n", slot.ID)
	fmt.Fprintf(&b, "ENABLED=%s\n", bit(cfg.Enabled))
	fmt.Fprintf(&b, "PENDING=%s\n", bit(cfg.Pending))
	fmt.Fprintf(&b, "MODE=%s\n", modeName(cfg.Mode))
	fmt.Fprintf(&b, "ALLOW_PRIVATE=%s\n", bit(cfg.AllowPrivate))
	fmt.Fprintf(&b, "MTU=%d\n", cfg.MTU)
	fmt.Fprintf(&b, "NIC=%s\n", nic)
	fmt.Fprintf(&b, "REJECT4=\"%s\"\n", strings.Join(cfg.Policy().RejectPrefixes4(), " "))
	return b.String()
}

func modeName(mode proto.ExitMode) string {
	if mode == proto.ExitModeWstunnel {
		return string(proto.ExitModeWstunnel)
	}
	return string(proto.ExitModeNative)
}

// writeSlotFiles renders and writes the three files under <n>/ the daemons and
// S94exit read. Mode 0600: the restriction yaml carries the token.
func writeSlotFiles(slot Slot, cfg Config, nic string) error {
	if err := os.MkdirAll(slot.Dir(), 0o700); err != nil {
		return fmt.Errorf("create %s: %w", slot.Dir(), err)
	}
	for _, f := range []struct {
		path, content string
	}{
		{slot.HevConfigPath(), RenderHevConfig(slot, cfg)},
		{slot.RestrictPath(), RenderRestrict(slot, cfg)},
		{slot.EnvPath(), RenderEnv(slot, cfg, nic)},
	} {
		if err := utils.WriteFileAtomic(f.path, []byte(f.content), 0o600); err != nil {
			return err
		}
	}
	return nil
}
